build:
    environment:
        php:
            version: 7.1

filter:
    paths: ['src/*']
    excluded_paths: ['src/*/*/*/Tests/*']

before_commands:
    - "composer install --no-dev --prefer-source"

tools:
    sensiolabs_security_checker: true
    php_mess_detector:
        enabled: true
    php_analyzer:
        enabled: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_pdepend:
        enabled: true
        excluded_dirs: ["tests", "vendor"]
    external_code_coverage:
        timeout: 3600
    php_code_coverage:
        enabled: true
