parameters:
    cem_mail.mail.service.class: CEM\Infrastructure\MailBundle\Service\MailerService

services:
    cem_mail.mail.service:
        class: "%cem_mail.mail.service.class%"
        calls:
            - [setMailer, ["@mailer"]]
