instances:
    type: "rest"
    resource: "@CemApiBundle/Controller/VmController.php"
    name_prefix:  "api_"

favorites:
    type: "rest"
    resource: "@CemApiBundle/Controller/VmBookmarksController.php"
    name_prefix:  "api_"
