imports:
    - { resource: config_test.yml }

parameters:
    database_host: localhost
    host.api: api.cem.local
    host.doc: developers.cem.local
    host.dashboard: dashboard.cem.local
    host.oauth: oauth.cem.local
