app_oauth_server:
    host: "%host.oauth%"
    resource: "@CemApiBundle/Resources/config/routing/oauth.yml"

adb_api:
    type:     "rest"
    schemes:  ["http"]
    host:     "%host.api%"
    resource: "@CemApiBundle/Resources/config/routing/api.yml"

NelmioApiDocBundle:
    prefix:   "/doc"
    schemes:  ["http"]
    host:     "%host.doc%"
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"

app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation
