parameters:
    cem_user.repository.user.orm.class: CEM\Infrastructure\UserBundle\Repository\DoctrineUserRepository
    cem_user.model.user.class: CEM\Infrastructure\UserBundle\Model\User
    cem_user.user_provider.class: CEM\Infrastructure\UserBundle\Security\Provider\UserProvider

services:
    cem_user.repository.user.orm:
        class: "%cem_user.repository.user.orm.class%"
        public: false
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - "%cem_user.model.user.class%"

    cem_user.user_provider:
      class: "%cem_user.user_provider.class%"
      arguments: ["@cem_user.repository.user.orm"]
