parameters:
    cem_virtual_machine.vm.repository.ec2.class: CEM\Infrastructure\VirtualMachineBundle\Repository\Ec2VmRepository
    cem_virtual_machine.vm.ec2_client.class: CEM\Infrastructure\VirtualMachineBundle\Client\Wrapper\Ec2ClientWrapper
    cem_virtual_machine.vm.factory.ec2.class: CEM\Infrastructure\VirtualMachineBundle\Factory\Ec2VmFactory
    cem_virtual_machine.vm.subscriber.notification.class: CEM\Infrastructure\VirtualMachineBundle\EventSubscriber\VmNotificationSubscriber
    cem_virtual_machine.vm.model.class: "\\CEM\\Domain\\VirtualMachine\\Model\\VirtualMachine"

services:
    cem_virtual_machine.vm.ec2_client:
        class: "%cem_virtual_machine.vm.ec2_client.class%"
        calls:
            - [setClient, ["@aws.ec2"]]

    cem_virtual_machine.vm.factory.ec2:
        class: "%cem_virtual_machine.vm.factory.ec2.class%"
        calls:
            - [setVmClass, ["%cem_virtual_machine.vm.model.class%"]]
            - [setEventDispatcher, ["@event_dispatcher"]]

    cem_virtual_machine.vm.repository.ec2:
        class: "%cem_virtual_machine.vm.repository.ec2.class%"
        public: false
        calls:
            - [setApiClient, ["@cem_virtual_machine.vm.ec2_client"]]
            - [setEventDispatcher, ["@event_dispatcher"]]
            - [setVmFactory, ["@cem_virtual_machine.vm.factory.ec2"]]

    cem_virtual_machine.vm.subscriber.notification:
        class: "%cem_virtual_machine.vm.subscriber.notification.class%"
        arguments:
            - "%cem_virtual_machine.notification%"
        calls:
            - [setMailerService, ["@cem_mail.mail.service"]]
            - [setTplEngine, ["@templating"]]
            - [setSecurityTokenStorage, ["@security.token_storage"]]
        tags:
            - { name: kernel.event_subscriber }
