parameters:
    cem_bookmark.bookmark.repository.db.class: CEM\Infrastructure\BookmarkBundle\Repository\VmBookmarkRepository
    cem_bookmark.bookmark.factory.class: CEM\Domain\Bookmark\Factory\VmBookmarkFactory
    cem_bookmark.bookmark.model.class: CEM\Domain\Bookmark\ValueObject\VmBookmark
    cem_bookmark.bookmark.listener.vm_load.class: CEM\Infrastructure\BookmarkBundle\EventListener\VmLoadedListener

services:
    cem_bookmark.bookmark.repository:
        alias: cem_bookmark.bookmark.repository.db

    cem_bookmark.bookmark.repository.db:
        class: "%cem_bookmark.bookmark.repository.db.class%"
        public: false
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - "%cem_bookmark.bookmark.model.class%"

    cem_bookmark.bookmark.factory:
        class: "%cem_bookmark.bookmark.factory.class%"
        calls:
            - [setBookmarkClass, ["%cem_bookmark.bookmark.model.class%"]]

    cem_bookmark.bookmark.listener.vm_load:
        class: "%cem_bookmark.bookmark.listener.vm_load.class%"
        calls:
            - [setSecurityTokenStorage, ["@security.token_storage"]]
            - [setBookmarkRepository, ["@cem_bookmark.bookmark.repository"]]
        tags:
            - { name: kernel.event_listener, event: cem_virtual_machine.vm.post_load, method: onVmPostLoad }
